; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[platformio]
name = gatr2-pico
description = RP2040 sensor firmware for GATR2
default_envs = hat2_bno08x

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#a1df30f
board = pico
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
lib_extra_dirs = third_party
build_flags = -I$PROJECT_DIR/../common
build_src_flags = -Wall -Wextra
build_src_filter = +<*> +<../../common/frame_codec.cpp>

[env:hat2_bno08x]
build_flags = ${env.build_flags} -DGATR2_HAT_REV=2 -DGATR2_IMU_BNO08X

[env:hat2_asm330]
build_flags = ${env.build_flags} -DGATR2_HAT_REV=2 -DGATR2_IMU_ASM330
lib_ignore = sh2
