; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[platformio]
name = gatr2-pico
description = RP2040 sensor firmware for GATR2

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#a1df30f
board = pico
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
build_flags = -I$PROJECT_DIR/../common
build_src_filter = +<*> +<../../common/frame_codec.cpp>
