#!/usr/bin/env bash
# Install on the Pi; --dry-run only renders the unit and never changes services.
set -euo pipefail

usage() {
    cat <<'EOF'
Usage: sudo bash tools/install_service.sh --user YOUR_PI_USER [options]

Start naviGATR at every boot, independently of login or network access.
Defaults to build-bench/navigatr and the Brain-profiled USB configuration.

  --user USER     Account that runs naviGATR (default: sudo's invoking user)
  --binary PATH   Built Linux executable (default: PROJECT/build-bench/navigatr)
  --config PATH   Main XML (default: PROJECT/config/override/brain_profile_usb.xml;
                  RS-485: config/override/brain_profile_rs485.xml)
  --dry-run       Print the proposed unit without installing or starting anything
  --help          Show this message

Relative option paths are relative to your current directory. The checkout,
binary and config paths must not contain spaces or shell/systemd metacharacters.
Stop any manually launched naviGATR before installing. The installer enables
and restarts navigatr.service; it never builds, flashes, or changes networking.
EOF
}

fail() { printf 'Error: %s\n' "$*" >&2; exit 1; }

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
project_dir=$(cd -- "$script_dir/.." && pwd)
service_user=${SUDO_USER:-${USER:-}}
binary="$project_dir/build-bench/navigatr"
config="$project_dir/config/override/brain_profile_usb.xml"
dry_run=false

while (($#)); do
    case "$1" in
        --user|--binary|--config)
            (($# >= 2)) && [[ -n $2 && $2 != --* ]] || fail "$1 needs a value"
            case "$1" in
                --user) service_user=$2 ;;
                --binary) binary=$2 ;;
                --config) config=$2 ;;
            esac
            shift 2
            ;;
        --dry-run) dry_run=true; shift ;;
        --help|-h) usage; exit 0 ;;
        *) fail "Unknown option: $1 (see --help)" ;;
    esac
done

[[ $service_user =~ ^[a-zA-Z_][a-zA-Z0-9_-]*$ ]] || fail 'Specify a valid --user account'
[[ -f $binary && -x $binary ]] || fail "Executable not found: $binary; build it on the Pi first"
[[ -f $config ]] || fail "Configuration not found: $config"
binary=$(realpath -e -- "$binary")
config=$(realpath -e -- "$config")
for path in "$project_dir" "$binary" "$config"; do
    [[ $path =~ ^/[a-zA-Z0-9_./-]+$ ]] || fail "Use paths without spaces or special characters: $path"
done

if ! $dry_run; then
    [[ $(uname -s) == Linux ]] || fail 'Install this service on the Raspberry Pi, not on the host computer'
    ((EUID == 0)) || fail 'Installation needs sudo; --dry-run does not'
    id "$service_user" >/dev/null 2>&1 || fail "No such account: $service_user"
    for command in systemctl systemd-analyze getent install mktemp; do
        command -v "$command" >/dev/null || fail "Required command missing: $command"
    done
    [[ -d /run/systemd/system ]] || fail 'systemd is not running on this machine'
    for group in dialout gpio; do
        getent group "$group" >/dev/null || fail "Missing Raspberry Pi OS device-access group: $group"
    done
fi

render_unit() {
    cat <<EOF
# Generated by naviGATR tools/install_service.sh.
[Unit]
Description=naviGATR localization and inspection
StartLimitIntervalSec=0

[Service]
Type=exec
User=$service_user
SupplementaryGroups=dialout gpio
WorkingDirectory=$project_dir
ExecStart=$binary --config_file=$config
Restart=always
RestartSec=3
TimeoutStopSec=15
StandardOutput=journal
StandardError=journal
SyslogIdentifier=navigatr

[Install]
WantedBy=multi-user.target
EOF
}

if $dry_run; then
    render_unit
    exit 0
fi

temp_dir=$(mktemp -d)
trap 'rm -f -- "$temp_dir/navigatr.service"; rmdir -- "$temp_dir"' EXIT
render_unit > "$temp_dir/navigatr.service"
systemd-analyze verify "$temp_dir/navigatr.service"

unit_path=/etc/systemd/system/navigatr.service
if [[ -e $unit_path ]]; then
    backup=$(mktemp /etc/systemd/system/navigatr.service.backup.XXXXXX)
    install -m 0644 "$unit_path" "$backup"
    printf 'Previous unit saved to %s\n' "$backup"
fi
install -m 0644 "$temp_dir/navigatr.service" "$unit_path"
systemctl daemon-reload
systemctl enable navigatr.service
systemctl restart navigatr.service
printf '\nInstalled and enabled navigatr.service for %s.\n' "$service_user"
printf 'Check startup: systemctl status navigatr.service --no-pager\n'
printf 'Read logs:     journalctl -u navigatr.service -b -n 80 --no-pager\n'
printf 'Service startup alone does not establish sensor or Brain-link health.\n'
