// Generated by navigatr_field_refs from pi/naviGATR/config/override/field.xml. Do not edit.
#pragma once
#include "investigatr/reference.h"
struct Field : investigatr::FieldReferences {
    static constexpr investigatr::MapId kMapId    = 0xF6B3F2C9;
    static constexpr uint16_t           kRevision = 1;
    static constexpr investigatr::Reference NeutralGoal4North = investigatr::Reference::object(1, kMapId);
    static constexpr investigatr::Reference BlueGoal3North = investigatr::Reference::object(2, kMapId);
    static constexpr investigatr::Reference NeutralGoal1West = investigatr::Reference::object(3, kMapId);
    static constexpr investigatr::Reference BlueGoal2East = investigatr::Reference::object(4, kMapId);
    static constexpr investigatr::Reference NeutralGoal0Center = investigatr::Reference::object(5, kMapId);
    static constexpr investigatr::Reference RedGoal2West = investigatr::Reference::object(6, kMapId);
    static constexpr investigatr::Reference NeutralGoal1East = investigatr::Reference::object(7, kMapId);
    static constexpr investigatr::Reference RedGoal3South = investigatr::Reference::object(8, kMapId);
    static constexpr investigatr::Reference NeutralGoal4South = investigatr::Reference::object(9, kMapId);
};
